### ISSUE TITLE
Scoped creation of ArHeaderIterator in unittest

### ISSUE THREAD

**Issue by nordlow** [renatoathaydes/dar#1]
Line

https://github.com/renatoathaydes/dar/blob/364494cfa18c884621c9ea92a800e281e9e4daac/source/dar.d#L123

can be replaced by

```
scope ar = new ArHeaderIterator(file[8 .. $]);
```

to limit lifetime of `ar` to unittest.

**Comment by renatoathaydes** [comment]
Thanks for the hint, I will update.
